![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [ ]:
import numpy as np

import numpy as

In [28]:

my_array = np.arange[10]

print(my_array[9:1,-2])

TypeError: 'builtin_function_or_method' object is not subscriptable

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [12]:
print(my_array[8:6: -1])

[8, 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [11]:
print(my_array[2::-1])

[2, 1, 0]


In [30]:
## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas


SyntaxError: invalid decimal literal (2973827297.py, line 2)

In [34]:
matriz_4x5 = np.arange(1, 21).reshape(4, 5)
print(matriz_4x5)


matriz_4x5[::-1,::-1] #start, stop, step

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [38]:
matriz_4x5[0:2:1,0:2:1]

array([[1, 2],
       [6, 7]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [40]:
matriz_4x5[0::2,0::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [50]:
matriz_4x5[0:3:1,::-1] #para filas=[posicion inicial:posicion final exclusiva:pasos,] para columnas=[posicion inicial:posicion final exclusiva:pasos,]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [58]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
indices = np.where(x == "Loro")
print(indices)


(array([0, 3]),)


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [66]:
x = np.arange(20).reshape(2,5,2)
print(x)


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [67]:
matriz_4x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [72]:
matriz_4x5[::-1,::-1]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [ ]:
my_array11 = np.arange(11)

my_array11[3] =1

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [74]:
my_array49 = np.arange(10,50)

my_array49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [75]:
my_array49[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [86]:


vector = np.array([1, 2, 0, 0, 4, 0])

# Encontrar los índices de los valores que n
# .where(vector != 0)[0]
indices_no_cero = np.where(vector != 0)[0]

print(indices_no_cero)


[0 1 4]


In [81]:
vector.np.where !=0

NameError: name 'vector' is not defined

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [88]:
array = np.full((10,10),5)
array

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [94]:
np.amax(array)

np.amin(array)

np.int64(5)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [ ]:
vector_aleatorio = np.random.rand(30)

media_vector = np.mean(vector_aleatorio)

vector_aleatorio, media_vector


Result
(array([0.03547694, 0.57411642, 0.05358903, 0.93859339, 0.90685651,
        0.19487909, 0.93776047, 0.38698634, 0.09212227, 0.66959212,
        0.58968328, 0.3818069 , 0.21904437, 0.88172572, 0.97789603,
        0.10732649, 0.08319019, 0.57624488, 0.5935281 , 0.41253652,
        0.94072695, 0.65987218, 0.95382979, 0.50042053, 0.9697507 ,
        0.93687511, 0.86419071, 0.05028059, 0.9173931 , 0.22772191]),
 0.5544672205454724)

0.5544672205454724











## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
n = 5
array_cuadrado = np.ones((n, n))  # Matriz de 1s

# Rellenar el interior (sin contar el borde) con 0s
array_cuadrado[1:-1, 1:-1] = 0

array_cuadrado

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
matriz_8x8 = np.zeros((8, 8), dtype=int)


matriz_8x8[1::2, ::2] = 1  # Filas impares, columnas pares -> 1s
matriz_8x8[::2, 1::2] = 1  # Filas pares, columnas impares -> 1s

print(matriz_8x8)

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.