![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np


np.__version__

import numpy as np 

np.__version__

'2.1.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [23]:
mi_array = np.array([0,1,2,3,4,5,6,7,8,9])

mi_array = np.array([0,1,2,3,4,5,6,7,8,9])
mi_array = np.array([0,1,2,3,4,5,6,7,8,9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [24]:


array = np.full((3,3),True)

array


array = np.full((3,3)True)
array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [25]:

mi_array[mi_array%2 != 0]

mi_array[mi_array%2 !=0]

mi_array[mi_array%2 !=0]




array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [36]:

mi_array[mi_array%2 != 0] = -1
print(mi_array)

mi_array[mi_array%2 !=0] = -1
print(mi_array)

mi_array[mi_array%2 !=0] =-1
print(mi_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [39]:
array_where = np.where(mi_array%2 != 0, -1, mi_array) #esto el where tienes la condicion, y si se cumple pones -1 y so no al array
print(array_where)


array_where = np.where(mi_array%2 != 0, -1, mi_array)





[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [40]:
mi_array = mi_array.reshape(2,-1)
print(mi_array)

[[ 0 -1  2 -1  4]
 [-1  6 -1  8 -1]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [45]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate((a,b), axis = 0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [47]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
c = np.concatenate((a,b), axis = 1)
print(c) #cont

array([1])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

c= np.intersect1d(a, b)
print(np.intersect1d)

<function intersect1d at 0x000001CC42159940>


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [52]:
np.concatenate??

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [54]:
my_array = [0,1,2,3,4,5,6,7,8,9]

my_array = np.arrange(10)
print(my_array*10)#1

my_array[0] 
my_array[0,-1]
print(my_array[0,8])



0


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [56]:
my_matrix = np.array[(1,1,1),(1,1,1,)(1,1,1)]

<>:1: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24636\3822845410.py:1: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  my_matrix = np.array[(1,1,1),(1,1,1,)(1,1,1)]


TypeError: 'tuple' object is not callable

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [60]:
my_matrix = np.arange(50)
my_matrix[1:50:3]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [62]:
my_matrix_new = np.arange(4,1,-0.25)
my_matrix_new

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [ ]:
import matplotlib.pyplot as plt

imagen = plt.imread("./img/numpy.png")
print(imagen)

plt.imshow(imagen)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [ ]:
array_4 = np.array([[1], [2], [3], [4]])
array_4.reshape(2,2)



## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [65]:
secuencia_aleatoria = np.random.rand(4, 5, 3)

secuencia_aleatoria

#4: El número de "bloques" o matrices (la primera dimensión).
#5: El número de filas en cada matriz (la segunda dimensión).
#3: El número de columnas en cada matriz (la tercera dimensión)

array([[[2.23626718e-01, 8.87186556e-01, 9.81244568e-01],
        [8.64804732e-01, 9.74739897e-01, 6.29782859e-01],
        [5.18112223e-01, 2.34325375e-01, 3.20109404e-01],
        [8.30155726e-01, 5.00946509e-01, 2.72845500e-02],
        [3.62616092e-01, 2.92589336e-01, 5.55034458e-02]],

       [[8.17317794e-01, 5.66684574e-01, 8.30528920e-01],
        [6.83896781e-01, 3.95011132e-01, 6.54248979e-01],
        [4.33675979e-01, 2.46410532e-01, 5.87012361e-01],
        [4.24156551e-01, 7.62445884e-01, 1.86464319e-01],
        [6.38255432e-01, 9.39347693e-01, 7.75711269e-01]],

       [[9.01413465e-01, 2.27358979e-02, 7.96601626e-02],
        [1.15021744e-01, 5.89865336e-06, 9.60178297e-01],
        [3.33551152e-01, 7.47555031e-01, 7.43210458e-01],
        [6.94426247e-01, 6.35361158e-02, 9.70607588e-01],
        [1.95946993e-01, 6.89304531e-01, 5.98381915e-01]],

       [[1.12585004e-01, 5.19739818e-01, 6.97860406e-02],
        [7.74403047e-01, 2.63363986e-01, 2.60063103e-01],
        

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [ ]:
matriz_false_10x1 = np.full((10, 1), False)

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [ ]:
Pregunta Jose Luis 